# This is a basic workflow to help you get started with Actions

name: Sync with sourceforge svn

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install svn
        run: choco install sliksvn
        
      - name: checkout the SVN source
        run: |
          svn checkout svn://svn.code.sf.net/p/somfree/code/trunk somfree-code
          cd somfree-code
        shell: cmd
        
      - name: init GIT repo
        run: |
          git init
          echo .svn/ > .gitignore
          git add .gitignore; git commit -m 'Initial .gitignore'

      - name: Move SVN code to import-svn branch
        run: |
          git checkout -b import-svn
          git add -A
          git commit -m 'Initial SVN'

      - name: PULL GIT repo to original-git branch
        run: |
          git checkout -b import-git master
          git remote add original-git https://github.com/prokushev/somfree
          git pull original-git master
